### ISSUE TITLE
Can we have ability to suppress the "flutter: Could not find a path" console logging?

### ISSUE THREAD

**Issue by mjacobsca** [shareven/dijkstra#1]
I'm using this project in my app. It works GREAT. Thank you! But it logs hundreds and thousands of "flutter: Could not find a path" messages to the console. Is there a way we can disable that for release version apps? Or should I be catching those fails somehow? It's expected that some paths in my mapping app won't have solutions.

**Comment by shareven** [comment]
The version 0.0.3 removed the print .
